package com.thinking.ws.data_type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-13T20:01:26.548+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://data_type.ws.thinking.com/", name = "DataTypeWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DataTypeWS {

    @WebMethod
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetAllStudentsResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public com.thinking.ws.data_type.GetAllStudentsResponse.Return getAllStudents();

    @WebMethod
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetStudentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.thinking.ws.data_type.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.AddStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.thinking.ws.data_type.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStudentsByPrice", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetStudentsByPrice")
    @ResponseWrapper(localName = "getStudentsByPriceResponse", targetNamespace = "http://data_type.ws.thinking.com/", className = "com.thinking.ws.data_type.GetStudentsByPriceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.thinking.ws.data_type.Student> getStudentsByPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0
    );
}
