package com.thinking.ws.data_type;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-13T20:01:26.601+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "DataTypeWSImplService",
                  wsdlLocation = "http://192.168.1.196:8123/ws-demo/datattypews?wsdl",
                  targetNamespace = "http://data_type.ws.thinking.com/")
public class DataTypeWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://data_type.ws.thinking.com/", "DataTypeWSImplService");
    public final static QName DataTypeWSImplPort = new QName("http://data_type.ws.thinking.com/", "DataTypeWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.196:8123/ws-demo/datattypews?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataTypeWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.196:8123/ws-demo/datattypews?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataTypeWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataTypeWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataTypeWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DataTypeWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DataTypeWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DataTypeWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DataTypeWS
     */
    @WebEndpoint(name = "DataTypeWSImplPort")
    public DataTypeWS getDataTypeWSImplPort() {
        return super.getPort(DataTypeWSImplPort, DataTypeWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataTypeWS
     */
    @WebEndpoint(name = "DataTypeWSImplPort")
    public DataTypeWS getDataTypeWSImplPort(WebServiceFeature... features) {
        return super.getPort(DataTypeWSImplPort, DataTypeWS.class, features);
    }

}
