package ocpp.cp._2012._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-09-21T15:54:37.865+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "urn://Ocpp/Cp/2012/06/", name = "ChargePointService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChargePointService {

    @WebMethod(operationName = "Reset", action = "/Reset")
    @Action(input = "/Reset", output = "/ResetResponse")
    @WebResult(name = "resetResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public ResetResponse reset(
        @WebParam(partName = "parameters", name = "resetRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ResetRequest parameters
    );

    @WebMethod(operationName = "SendLocalList", action = "/SendLocalList")
    @Action(input = "/SendLocalList", output = "/SendLocalListResponse")
    @WebResult(name = "sendLocalListResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public SendLocalListResponse sendLocalList(
        @WebParam(partName = "parameters", name = "sendLocalListRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        SendLocalListRequest parameters
    );

    @WebMethod(operationName = "RemoteStartTransaction", action = "/RemoteStartTransaction")
    @Action(input = "/RemoteStartTransaction", output = "/RemoteStartTransactionResponse")
    @WebResult(name = "remoteStartTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public RemoteStartTransactionResponse remoteStartTransaction(
        @WebParam(partName = "parameters", name = "remoteStartTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        RemoteStartTransactionRequest parameters,
        @WebParam(partName = "chargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2012/06/", header = true)
        String chargeBoxIdentity
    );

    @WebMethod(operationName = "CancelReservation", action = "/CancelReservation")
    @Action(input = "/CancelReservation", output = "/CancelReservationResponse")
    @WebResult(name = "cancelReservationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public CancelReservationResponse cancelReservation(
        @WebParam(partName = "parameters", name = "cancelReservationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        CancelReservationRequest parameters
    );

    @WebMethod(operationName = "DataTransfer", action = "/DataTransfer")
    @Action(input = "/DataTransfer", output = "/DataTransferResponse")
    @WebResult(name = "dataTransferResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public DataTransferResponse dataTransfer(
        @WebParam(partName = "parameters", name = "dataTransferRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        DataTransferRequest parameters
    );

    @WebMethod(operationName = "GetConfiguration", action = "/GetConfiguration")
    @Action(input = "/GetConfiguration", output = "/GetConfigurationResponse")
    @WebResult(name = "getConfigurationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public GetConfigurationResponse getConfiguration(
        @WebParam(partName = "parameters", name = "getConfigurationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetConfigurationRequest parameters
    );

    @WebMethod(operationName = "GetDiagnostics", action = "/GetDiagnostics")
    @Action(input = "/GetDiagnostics", output = "/GetDiagnosticsResponse")
    @WebResult(name = "getDiagnosticsResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public GetDiagnosticsResponse getDiagnostics(
        @WebParam(partName = "parameters", name = "getDiagnosticsRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetDiagnosticsRequest parameters
    );

    @WebMethod(operationName = "ChangeAvailability", action = "/ChangeAvailability")
    @Action(input = "/ChangeAvailability", output = "/ChangeAvailabilityResponse")
    @WebResult(name = "changeAvailabilityResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public ChangeAvailabilityResponse changeAvailability(
        @WebParam(partName = "parameters", name = "changeAvailabilityRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ChangeAvailabilityRequest parameters
    );

    @WebMethod(operationName = "UpdateFirmware", action = "/UpdateFirmware")
    @Action(input = "/UpdateFirmware", output = "/UpdateFirmwareResponse")
    @WebResult(name = "updateFirmwareResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public UpdateFirmwareResponse updateFirmware(
        @WebParam(partName = "parameters", name = "updateFirmwareRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        UpdateFirmwareRequest parameters
    );

    @WebMethod(operationName = "RemoteStopTransaction", action = "/RemoteStopTransaction")
    @Action(input = "/RemoteStopTransaction", output = "/RemoteStopTransactionResponse")
    @WebResult(name = "remoteStopTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public RemoteStopTransactionResponse remoteStopTransaction(
        @WebParam(partName = "parameters", name = "remoteStopTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        RemoteStopTransactionRequest parameters
    );

    @WebMethod(operationName = "GetLocalListVersion", action = "/GetLocalListVersion")
    @Action(input = "/GetLocalListVersion", output = "/GetLocalListVersionResponse")
    @WebResult(name = "getLocalListVersionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public GetLocalListVersionResponse getLocalListVersion(
        @WebParam(partName = "parameters", name = "getLocalListVersionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetLocalListVersionRequest parameters
    );

    @WebMethod(operationName = "UnlockConnector", action = "/UnlockConnector")
    @Action(input = "/UnlockConnector", output = "/UnlockConnectorResponse")
    @WebResult(name = "unlockConnectorResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public UnlockConnectorResponse unlockConnector(
        @WebParam(partName = "parameters", name = "unlockConnectorRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        UnlockConnectorRequest parameters
    );

    @WebMethod(operationName = "ClearCache", action = "/ClearCache")
    @Action(input = "/ClearCache", output = "/ClearCacheResponse")
    @WebResult(name = "clearCacheResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public ClearCacheResponse clearCache(
        @WebParam(partName = "parameters", name = "clearCacheRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ClearCacheRequest parameters
    );

    @WebMethod(operationName = "ChangeConfiguration", action = "/ChangeConfiguration")
    @Action(input = "/ChangeConfiguration", output = "/ChangeConfigurationResponse")
    @WebResult(name = "changeConfigurationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public ChangeConfigurationResponse changeConfiguration(
        @WebParam(partName = "parameters", name = "changeConfigurationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ChangeConfigurationRequest parameters
    );

    @WebMethod(operationName = "ReserveNow", action = "/ReserveNow")
    @Action(input = "/ReserveNow", output = "/ReserveNowResponse")
    @WebResult(name = "reserveNowResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    public ReserveNowResponse reserveNow(
        @WebParam(partName = "parameters", name = "reserveNowRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ReserveNowRequest parameters
    );
}
