package com.thinking.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5 2018-08-15T13:38:09.682+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://ws.thinking.com/", name = "OrderWS")
@XmlSeeAlso({ ObjectFactory.class })
public interface OrderWS {

	@WebMethod
	@RequestWrapper(localName = "getOrderById", targetNamespace = "http://ws.thinking.com/", className = "com.thinking.ws.GetOrderById")
	@ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://ws.thinking.com/", className = "com.thinking.ws.GetOrderByIdResponse")
	@WebResult(name = "return", targetNamespace = "")
	public com.thinking.ws.Order getOrderById(@WebParam(name = "arg0", targetNamespace = "") int arg0);
}
