package com.thinking.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-09-07T10:02:05.375+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "urn://Ocpp/Cs/2012/06/", name = "TestService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestService {

    @WebMethod(operationName = "Authorize", action = "/Authorize")
    @Action(input = "Authorize", output = "AuthorizeResponse")
    @WebResult(name = "AuthorizeResponse", targetNamespace = "http://service.thinking.com/", partName = "parameters")
    public AuthorizeResponse authorize(
        @WebParam(partName = "parameters", name = "authorizeRequest", targetNamespace = "http://service.thinking.com/", header = true)
        AuthorizeRequest parameters
    );
}
